version: '3'
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    networks:
      - app-network
  backend:
    build: .
    ports:
      - '8080:8080'
    networks:
      - app-network
networks:
  app-network: