# Install rest client addon for vscode to test routes from this file

### Home path

GET http://localhost:8080/
Authorization: mysecrettoken

### 404 Path

GET http://localhost:8080/dsfgeghsdfghdfgdfagadrsg
Authorization: mysecrettoken

### without auth (any route)

GET http://localhost:8080/

### Time path
GET http://localhost:8080/time
Authorization: mysecrettoken

### Metrics path
GET http://localhost:8080/metrics
Authorization: mysecrettoken

### Docker test
GET http://localhost:49160/time
Authorization: mysecrettoken